version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-fruits
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: s04t02n02-app:latest
    container_name: s04t02n02-app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  mysql_data:
